package ru.dayone.lifestylehub.utils

enum class FailureCode {
    DEFAULT,
    GET_WEATHER_FAILED,
    GET_LOCATION_PERMISSION_DENIED,
    LOCATION_UNAVAILABLE,
    GET_PLACES_FAILED,
    GET_PLACE_DETAILS_FAILED,
    NO_ACTIVITY_BY_THIS_REQUEST
}